### PR TITLE
Add UDS support

### PR DESCRIPTION
**Pull request by xvello**
This PR adds support for submission of custom metrics through a Unix Socket on Linux.
See https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support for context and benefits.

Implementation details:

- no change in the public API, UDS mode is triggered by setting `0` as port, the socket path as `hostname`
- the send timeout is set at `100ms`. It only triggers if dogstatsd is overloaded/frozen and the socket buffer is full. The equivalent in UDP is a full reception buffer, triggering a silent packet drop
- the default behaviour of the library is to ignore all exceptions, but a custom handler can be passed. Documented the expected exceptions and their meaning

# Testing

- Reduced the parallelism of NonBlockingStatsDClientPerfTest (from 20 to 10) to reduce flakes on Travis
- Added the `UnixSocketTest` test class to test good transmission + error handling and recovery

# Windows

The feature is Linux only, and requires an external `jnr.unixsocket` JNI library. This library provides NOOP stubs for unsupported OSes, so the library still compiles and operates in UDP mode with no dark magic.

Tests pass on windows, all of the `UnixSocketTest` class is ignored of course. As with Linux, the `NonBlockingStatsDClientPerfTest` test is still a bit flaky.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.timgroup.statsd.EventTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec
Running com.timgroup.statsd.NonBlockingStatsDClientPerfTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.172 sec
Running com.timgroup.statsd.NonBlockingStatsDClientTest
Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.703 sec
Running com.timgroup.statsd.UnixSocketTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec

Results :

Tests run: 51, Failures: 0, Errors: 0, Skipped: 1
```

### CODE REVIEW

**Comment by erks** [comment]
Hi @xvello @masci, any ETA on when this can be merged?

**Comment by xvello** [comment]
Hello @erks,

The code is manually tested and ready for code review, I need to work on the unit testing before merging it. As we are currently focusing on the 6.2.0 release, I hope I'll be able to return to it in 2 weeks.

In the meantime, feedback on the PR and testing with your use case would be greatly appreciated.

**Comment by xvello** [comment]
@nmuesch @masci Tests are green and documentation is updated, 

@erks Did you have time to test the branch yet?

**Comment by erks** [comment]
@xvello No, I did not, unfortunately.

**Comment by sean-madden** [comment]
Any update on this PR? Exciting feature!

**Comment by nmuesch** [comment]
Hey, apologies for the delay. Having a look at this today! Thanks for the improvements!!

**Pull request merged**
