### PR TITLE
Add more Client implementation for better flexibility

### PR DESCRIPTION
**Pull request by pgelinas**
I've added two new StatsDClient implementation: a Blocking Client and a Concurrent Client.

The Blocking client is as advertised: the IO Operation is done in the calling thread and is thus blocking until the return of the IO Call. Useful for cases when the consumer of the library wants finer-ish control of the IO Operation. 

The Concurrent client is for cases when the client is used by lots of producer threads: the NonBlocking client has a high contention on the queue lock since it's a BlockingQueue. The Concurrent client uses a non-blocking, lock-free queue for enqueue metrics to the Background IO Thread. It provides higher throughput for the producer case (up to 2x in my case). The downside is that the IO Thread needs to `Thread.sleep()` when there is no message in queue, making it less responsive to new metrics.

This is a first draft, I plan to add more Javadoc soon and also fix a HotSpot inside the metric client found during performance testing of my application.

### CODE REVIEW

**Comment by masci** [comment]
Thanks @pgelinas please ping me when this is good to go (more Javadocs will be much appreciated 😄 )

**Comment by pgelinas** [comment]
Well..... the test for the Blocking client seems to fail on Travis but not locally... I'll have to dig into that because that's WEIRD.

**Comment by pgelinas** [comment]
Seems like I'm able to reproduce the failures locally, but it's random and changes from test run to test run. This makes me suspect UDP packet loss... nothing inherent to the patch. I'll try to come up with an update to the perf test, something to make the test accept a 1% difference or something.

**Comment by pgelinas** [comment]
Well.... I'm out of ideas. The fix worked locally, but still won't work on Travis. If you've got any idea, let me know.

Otherwise, on the Client implementation side, I'm done. Any comments welcome :)

**Comment by xvello** [comment]
Hi @pgelinas 

To me, it looks like the SynchronizedBlockingStatsDClient test fails because [we timeout on the sending loop](https://github.com/pgelinas/java-dogstatsd-client/blob/8579fa42acaf7290ea79e85c101f8f9381955aa5/src/test/java/com/timgroup/statsd/NonBlockingStatsDClientPerfTest.java#L86) but the exception is ignored instead of failing the test. Then, we proceed to the `assertTrue` which fails because we did not send all the data.

It's normal for this client to take longer than non-blocking clients to send as much data, as it is blocking. Furthermore, shared travis runners are obviously slower than local testing, this might explain why your test pass locally.

Could you try:

- getting `InterruptedException` to fail the test instead of proceeding to the count, to confirm this hypothesis
- make the 20 seconds send timeout longer for that client alone
- remove the `1%` tolerance and go back to exact equality, as even 1% loss might be unacceptable to some users

Cheers

**Comment by xvello** [comment]
@pgelinas As I'm working on https://github.com/DataDog/java-dogstatsd-client/pull/42 , I'd like to synchronise with you about merging. I'm OK rebasing on `master` once your PR is merged, but do you have any bandwidth to work on the testing fixes in the upcoming days?

If now, would you be OK rebasing on my PR? Changes are pretty contained.

**Comment by pgelinas** [comment]
I can take a look at this today. However, the failure is not constrained to
the blocking client: I've been able to reproduce the same issue locally,
but randomly happening on all the clients implementation.

2018-01-08 10:18 GMT-05:00 Xavier Vello <notifications@github.com>:

**Comment by xvello** [comment]
Could you try cherry-picking https://github.com/DataDog/java-dogstatsd-client/pull/42/commits/9279011febdedfd42901488c3754828be8b95210 ?
Running `RAND.nextInt()` on shared CI runners just for the sake of it does not look like a great idea.

**Comment by pgelinas** [comment]
I can, but I doubt it'll change anything. The failures are most likely
caused by UDP packet loss, even on localhost connection. There's no
reliability with UDP, so having a test that expect the server to receive
all the packet without any sort of ACK/retry is prone to these random
failures.

2018-01-08 12:38 GMT-05:00 Xavier Vello <notifications@github.com>:

**Comment by pgelinas** [comment]
@xvello I've also re-read your first comment:

> remove the 1% tolerance and go back to exact equality, as even 1% loss might be unacceptable to some users

This can't be achieved with UDP as you have no reliability guarantee and the library doesn't provide TCP capabilities even though StatsD does.

**Comment by pgelinas** [comment]
Ok, I've got a solution to remove the 1% loss: I've reworked the code a bit to abstract the UDP communication layer out of the client, so a unit test can provide a fake communication layer that doesn't do IO. That way, the perf test can do it's work without the unreliability of UDP.

As a bonus, that opens the door for providing a TCP alternative.

**Comment by xvello** [comment]
Hi @pgelinas ,

Did you push the code? FYI I am working on [Unix Domain Socket](https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support) support as an alternative to UDP. This is supported by DSD6 and allows:

- error detection
- easier communication on docker environments
- docker container tagging

**Comment by pgelinas** [comment]
I should do it soon. I'm polishing the stuff with more Javadocs and I got caught up in more pressing work 😃

**Comment by xvello** [comment]
Green travis, that's great to see! Will review this afternoon

**Comment by pgelinas** [comment]
Rebased on top of master following the last merge, updated the patch with the new distribution API.

**Pull request closed without merging**
